language: generic

addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - ack-grep
      
before_install:
  - chmod +x ci/spellcheck.sh
  - sudo ln -sf /usr/bin/ack-grep /usr/local/bin/ack
      
script: ./ci/spellcheck.sh

branches: 
  only:
    - gh-pages 
    - /.*/
