# Site settings
title: Jamie Blog
description: >
  The Void
baseurl: ""
url: "https://dengjianping.github.io/"
github_username: Dengjianping

# Build settings
highlighter: rouge

root: https://dengjianping.github.io/
